

FROM ubuntu:23.04
RUN apt update 
RUN apt install -y nginx
RUN apt install -y certbot

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN certbot renew --dry-run

CMD ["nginx", "-g", "daemon off;"]